version: '3'

services:
  base-sepolia:
    image: ghcr.io/openvino/base-sepolia:latest
    restart: always
    hostname: base-sepolia.base-sepolia.dappnode
    ports:
      - "8545:8545"
      - "6060:6060"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - base_sepolia_data:/data
      - jwt_shared:/jwt/jwt.hex
    networks:
      - base-sepolia-test

volumes:
  base_sepolia_data:
  jwt_shared:

networks:
  base-sepolia-test:
    external: true
