services:
  base-sepolia:
    image: ghcr.io/openvino/base-sepolia:latest
    container_name: base-sepolia
    restart: always
    hostname: base-sepolia.base-sepolia.dappnode
    ports:
      - "8545:8545"     # JSON-RPC (HTTP)
      - "8551:8551"     # Engine API (auth)
      - "6060:6060"     # Prometheus metrics
      - "30303:30303/tcp"
      - "30303:30303/udp"
    command: >
      --chain sepolia
      --datadir /data
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret /jwt/jwt.hex
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --metrics 0.0.0.0:6060
    volumes:
      - base_sepolia_data:/data
      - jwt_shared:/jwt:ro
    networks:
      base-sepolia-test:
        aliases:
          - reth

volumes:
  base_sepolia_data:
  jwt_shared:
    external: true

networks:
  base-sepolia-test:
    external: true

